var crypto = require("crypto");
var template = require("./template.json");

/**
 * This utility generates random cards for printing with adminpanel/idcards
 * e.g. for visitors or for students that lost their cards, to have some pre-made cards in stock
 * That way, students can just get their QR-ID changed to that of their new card, visitors
 * are registered with a QR-ID preset
 *
 * QR-IDs generated using this utility have a prefix, so that they can be distinguished
 * and so that they don't collide with QR-IDs randomly generated by the API server
 */

var prefix = process.argv[2];
var number_str = process.argv[3];
if (isNaN(number_str)) {
	console.log("Invalid command! Usage:");
	console.log("   node gencards.js <prefix> <number>");
	console.log("   > prefix: qrid prefix, e.g. vis_");
	console.log("   > number: number of entries to generate");
	process.exit(1);
}
var number = parseInt(number_str);
var used_qrids = [];
var generated = [];

while (generated.length < number) {
	var st = JSON.parse(JSON.stringify(template));
	st.qrid = prefix + crypto.randomBytes(3).toString("hex");
	if (used_qrids.indexOf(st.qrid) > -1) continue;
	used_qrids.push(st.qrid);
	generated.push(st);
}
console.log(JSON.stringify(generated, null, 2));
